### ISSUE TITLE
install.php on php8 is broken

### ISSUE THREAD

**Issue by perdedora** [Circlepuller/Tinyboard#13]
If you tried to run install.php with php8.0 for some reason it won't work because of verbose_errors. 
Setting verbose_errors to false and will work.

Fatal error: Uncaught Exception: Template file 'error.html' does not exist or is empty in ''! in /var/www/Tinyboard/inc/template.php:69 Stack trace: #0 /var/www/Tinyboard/inc/display.php(91): Element() #1 /var/www/Tinyboard/inc/functions.php(380): error() #2 [internal function]: verbose_error_handler() #3 /var/www/Tinyboard/inc/functions.php(145): file_put_contents() #4 /var/www/Tinyboard/install.php(6): loadConfig() #5 {main} thrown in /var/www/Tinyboard/inc/template.php on line 69 Warning: Undefined array key "syslog" in /var/www/Tinyboard/inc/display.php on line 40 Warning: Undefined array key "debug" in /var/www/Tinyboard/inc/display.php on line 52 Warning: Undefined array key "debug" in /var/www/Tinyboard/inc/display.php on line 56 Warning: Undefined array key "password" in /var/www/Tinyboard/inc/display.php on line 70 Warning: Undefined array key "template" in /var/www/Tinyboard/inc/template.php on line 69 Fatal error: Uncaught Exception: Template file 'error.html' does not exist or is empty in ''! in /var/www/Tinyboard/inc/template.php:69 Stack trace: #0 /var/www/Tinyboard/inc/display.php(91): Element() #1 /var/www/Tinyboard/inc/functions.php(380): error() #2 /var/www/Tinyboard/inc/display.php(40): verbose_error_handler() #3 /var/www/Tinyboard/inc/functions.php(356): error() #4 [internal function]: fatal_error_handler() #5 {main} thrown in /var/www/Tinyboard/inc/template.php on line 69

**Comment by Circlepuller** [comment]
I'm pretty sure this is the lack of PHP 8 support on Twig 2. I've managed to update Twig to 3 on an upcoming commit, so hopefully that will address this issue.
